### ISSUE TITLE
Will this mod get an update for a SotV?

### ISSUE THREAD

**Issue by MeatMorning** [ZeusesNeckMeat/RiskOfRain2-ItemRoulette#10]

**Comment by ZeusesNeckMeat** [comment]
Hello. Yes, I do plan on updating this for SotV. I haven't had the chance to look at it since the release of the DLC, but I do plan on starting on the update soon.

**Comment by MeatMorning** [comment]
Fine, really like your mod - it makes heavily modded profiles much more bearable and replayable

**Comment by ZeusesNeckMeat** [comment]
I started work on updating the mod tonight. It's more involved than I was originally expecting so it might take a little while longer, however it's still going to be updated.

**Comment by ZeusesNeckMeat** [comment]
Hey there. Just wanted to update you on the status of the mod update. It's taken me a while to get enough time to figure out what it took to update, however it's finally be updated to work with SotV. If you're still interested, you should be good to download the newest update in R2ModMan and start using it again.
