### ISSUE TITLE
Option to have more guaranteed items per tier

### ISSUE THREAD

**Issue by MightyW0lf** [ZeusesNeckMeat/RiskOfRain2-ItemRoulette#7]
See title. Also the config fields for guaranteed items say "Items", not "Item", which is kinda confusing right now.

**Comment by ZeusesNeckMeat** [comment]
Ah, I forgot to update the config fields. I originally started out with trying to allow multiple items, however I wasn't able to figure out a way that was easy to understand and use. With that I figured getting it out with at least allowing a single item would be nice. 

I've been working on adding this ability over the past few days during my free time, and I'm hoping I can have an update with this by the end of the week.

**Comment by ZeusesNeckMeat** [comment]
Hey, this should be completed now. I haven't had as much time as I would like to do as thorough testing as I usually do, but from what I did test it looks good to me. I'll leave this open for another day or two and if you notice anything weird feel free to leave a comment letting me know what's going on!

**Comment by ZeusesNeckMeat** [comment]
Marking this as closed since I haven't heard anything about this being broken from anyone. Also added a few new config values to be able to control the "Should only use guaranteed items" for each tier, instead of a single global setting. Thanks for the feedback!
